# Development overrides for docker-compose
version: '3.8'

services:
  claude-api:
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
      - LOG_FORMAT=text
      - ALLOW_ORIGINS=["*"]
      - ALLOW_CREDENTIALS=true
    volumes:
      # Mount source code for hot reloading in development
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    
  # Development database (if needed in future)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"